### PR TITLE
Improve core commands

### PR DESCRIPTION
**Pull request by feikname**
Current changes:
 * Make `/client` also work with no target player
 * Add help messages for all current core commands (#199)
 * Add a message in /script for when no scripts are enabled

### CODE REVIEW

**Comment by NotAFile** [comment]
We seem to disagree on style here a bit.

I describe what the user wants to  "Ban a player" and you describe what the command does "Bans the player". I of course think the first style reads a lot better in-game, but we should agree on the style here.

**Comment by NotAFile** [comment]
Is this still WIP? Or can we target this at 0.1.1

**Comment by feikname** [comment]
Feel free to merge it :)

**Comment by swalladge** [comment]
Personally I prefer help messages in the imperative too. It just seems to sound better. ¯\\_(ツ)_/¯

There are also a couple of typos to be fixed once we decide on a style (descriptive vs imperative).

**Pull request merged**
