### PR TITLE
Use upstream enet

### PR DESCRIPTION
**Pull request by swalladge**
- removes all enet sources and associated setup scripts from piqueserver
- update dependencies to use `pyenet` from pypi
- enables installing piqueserver in develop/edit mode, since we don't have the hacks around installing enet
- should point out that the 'upstream enet' is our fork at <https://github.com/piqueserver/pyenet/> (which is the source for the pypi package as well)

### CODE REVIEW

**Comment by NotAFile** [comment]
Just going to merge this since it LGTM and noway is MIA

**Comment by noway** [comment]
LGTM 👍

**Comment by noway** [comment]
The only thing I see is that some old as scripts might get broken, but that only accounts to fixing import statement in them really.

**Comment by NotAFile** [comment]
Well that ship has sailed long ago really. We could still add a "from enet import *" enet.py file if we really wanted and then whack a `DeprecationWarning` in there.

**Comment by noway** [comment]
It's fine not to support old import statements, as long as it is straightforward to fix.

DeprecationWarning would be nice

**Comment by NotAFile** [comment]
we can however remove the sys.path hacks for enet

**Pull request merged**
