### PR TITLE
Improve docker image

### PR DESCRIPTION
**Pull request by godwhoa**
Removes source code after everything is installed.
Image size gets reduced by 71 MB.
Fixes SSL support.

### CODE REVIEW

**Comment by NotAFile** [comment]
have you tested this, I wonder? Doesn't seem like it should work?

**Comment by NotAFile** [comment]
so, how does it load the python files then? How does it load python files you haven't loaded before?

**Comment by NotAFile** [comment]
ah, it runs setup.py install, I see

**Comment by noway** [comment]
NICE

**Pull request merged**
