### PR TITLE
Show client info in status server

### PR DESCRIPTION
**Pull request by godwhoa**
Closes: #273

### CODE REVIEW

**Comment by swalladge** [comment]
Nice! Perhaps you could make `get_client_string` a method of `player`?

**Comment by NotAFile** [comment]
Or, even better, a client_info data class, with a __str__ method

**Comment by godwhoa** [comment]
@NotAFile That feels overkill
How about a `client_string` property of player?

**Comment by swalladge** [comment]
@godwhoa perfect - the client_string only needs to be calculated once on player connect then. :+1:

**Comment by godwhoa** [comment]
@swalladge Meant something like this:
```python
    @property
    def client_string(self):
        client = self.client_info.get("client", "Unknown")
        os = self.client_info.get("os_info", "Unknown")
        version = self.client_info.get("version", None)
        if version:
            version_string = ".".join(map(str, version))
        else:
            version_string = "Unknown"
        return "{} v{} on {}".format(client, version_string, os)
```

**Comment by swalladge** [comment]
How about

```
def on_connect(self):
    ...
    self.client_string = self._get_client_string()

def _get_client_string(self):
   client = self..... etc.
```

**Comment by godwhoa** [comment]
@swalladge client_info wouldn't be populated on connect. 
`on_version_info_recieved` would be the right hook for your idea but we also have to deal with clients that don't send version info(eg. Voxlap).
Going with `client_string` `@property` since it's more straightforward.

**Comment by NotAFile** [comment]
+1, I highly prefer property over setting a string somewhere and then needing to refresh it in various places.

**Pull request merged**
