### PR TITLE
WIP: Python 3 compatibility

### PR DESCRIPTION
**Pull request by feikname**
This is the *work-in-progress* pull request for providing python3 compatibility

Main changes were provided by @NotAFile

### CODE REVIEW

**Comment by feikname** [comment]
That was weird. git bug?

**Comment by feikname** [comment]
I will solve merge conflicts after #61 is merge, to prevent extra work.

**Comment by feikname** [comment]
Closing temporarily...

**Comment by NotAFile** [comment]
Yes, I think work on this should be suspended temporarily, until we have tests. The str/unicode switch really hits this hard, since mat decided to (ab)use strings to store binary data

**Pull request closed without merging**
