### PR TITLE
Format C/C++ files

### PR DESCRIPTION
**Pull request by godwhoa**
used clang-format with "Visual Studio" style

### CODE REVIEW

**Comment by feikname** [comment]
Since this doesn't really modify any code besides aesthetically, I believe it's good to merge.

**Comment by NotAFile** [comment]
This kills the git diff history once, but having a consistent style is totally worth it

**Comment by swalladge** [comment]
Just a request: could the formatting style of choice be documented somewhere so we can auto format any new/changed code in the future?

**Comment by godwhoa** [comment]
@swalladge added a .clang-format file with defined style. You can just do `clang-format -i <file>` from now on and it'll use that

**Comment by swalladge** [comment]
Hmm just ran clang-format and it did some small changes. Curious as to why...? Maybe something you or I are using has some other config in the background? Diff for reference:

```
diff --git a/pyspades/bytes_c.cpp b/pyspades/bytes_c.cpp
index b1ce90d..36103ff 100644
--- a/pyspades/bytes_c.cpp
+++ b/pyspades/bytes_c.cpp
@@ -17,10 +17,10 @@
     along with pyspades.  If not, see <http://www.gnu.org/licenses/>.
 */
 
+#include "Python.h"
 #include <iostream>
 #include <sstream>
 #include <string>
-#include "Python.h"
 using namespace std;
 
 stringstream *create_stream()
diff --git a/pyspades/classicgen_c.cpp b/pyspades/classicgen_c.cpp
index 3524b4b..5a2c1e9 100644
--- a/pyspades/classicgen_c.cpp
+++ b/pyspades/classicgen_c.cpp
@@ -24,8 +24,8 @@ Ken Silverman
 http://moonedit.com/tom/vox1_en.htm#genland
 */
 
-#include "vxl_c.h"
 #include "constants_c.h"
+#include "vxl_c.h"
 
 #define OCTMAX 10 //how many sub functions(10)
 #define EPS 0.1f  //color smoothing (0.1)
@@ -124,7 +124,7 @@ static void noiseinit()
         noisep15[i] = noisep[i] & 15;
 }
 
-double noise3d (double fx, double fy, double fz, int mask)
+double noise3d(double fx, double fy, double fz, int mask)
 {
     int i, l[6], a[4];
     float p[3], f[8];
@@ -157,8 +157,8 @@ double noise3d (double fx, double fy, double fz, int mask)
     // clang-format on
 }
 
-vcol buf[VSID*VSID];
-vcol amb[VSID*VSID]; // ambient
+vcol buf[VSID * VSID];
+vcol amb[VSID * VSID]; // ambient
 
 inline int get_height_pos(int x, int y)
 {
@@ -176,10 +176,10 @@ inline int get_lowest_height(int x, int y)
 {
     int z = get_height(x, y, 63);
     z = max(get_height(x - 1, y, z),
-        max(get_height(x + 1, y, z),
-        max(get_height(x, y - 1, z),
-        max(get_height(x, y + 1, z),
-            z))));
+            max(get_height(x + 1, y, z),
+                max(get_height(x, y - 1, z),
+                    max(get_height(x, y + 1, z),
+                        z))));
     return z;
 }
 
diff --git a/pyspades/vxl_c.cpp b/pyspades/vxl_c.cpp
index 7e28177..5ead515 100644
--- a/pyspades/vxl_c.cpp
+++ b/pyspades/vxl_c.cpp
@@ -18,8 +18,8 @@
 
 */
 
-#include "Python.h"
 #include "vxl_c.h"
+#include "Python.h"
 #include <vector>
 
 using namespace std;
diff --git a/pyspades/world_c.cpp b/pyspades/world_c.cpp
index 2265587..bd475d2 100644
--- a/pyspades/world_c.cpp
+++ b/pyspades/world_c.cpp
@@ -18,8 +18,8 @@
 
 */
 
-#include "vxl_c.h"
 #include "constants_c.h"
+#include "vxl_c.h"
 
 // from vxl.h
 #define CHUNK 1023 //zlib buffer size
@@ -43,8 +43,8 @@
 
 // common.h
 #define CUBE_ARRAY_LENGTH 64
-#include <cmath>
 #include "common_c.h"
+#include <cmath>
 
 enum damage_index
 {
```

**Comment by swalladge** [comment]
LGTM :+1:

**Pull request merged**
