### PR TITLE
Fix copy-config execution

### PR DESCRIPTION
**Pull request by godwhoa**
closes: #248

### CODE REVIEW

**Comment by godwhoa** [comment]
> Also copy-config and update-geoip should be able to be given at the same time in args.

Ah didn't think about that. LGTM.

**Comment by NotAFile** [comment]
I'm really not a fan of the sys.exit(main()), and of returning 1/0. This is for a number of reasons:

1) it's not immediately obvious what those values do, their effects are way higher up in the call stack.

2) It's reinventing C-style error handling. Why? Python already has exceptions.

I agree that all sys.exit() should be as close to main() as possible, however this is taking it a step too far IMO

**Comment by swalladge** [comment]
Ok that's fine. Perhaps change it to return True/False, and sys.exit(1) if `main()` returns False?

**Comment by NotAFile** [comment]
I think it should raise OSError or some other exception and then catch it and raise(1), else do nothing

**Pull request merged**
