### PR TITLE
WIP: lint and tidy files

### PR DESCRIPTION
**Pull request by swalladge**
Time to tidy everything!

- [x] pylinting with travis
- [x] fix line endings
- [x] gitattributes file
- [x] editorconfig config file
- [x] make files conform to linting standards (well at least the piqueserver core source files)

### CODE REVIEW

**Comment by swalladge** [comment]
Quick update:

- feature_server is now renamed to piqueserver (doesn't change anything, since it has been for a while installed as the `piqueserver` module)
- gitattributes and editorconfig files added with settings that follow the wiki guidelines
- all (at least all I've discovered) piqueserver and pyspades source files should have correct line endings, no trailing spaces, and no tabs now
- there is now a pylintrc with global config we want - I've added some things to ignore in it based on patterns seen throughout the code - we'll probably want to stop ignoring some things once the major lint issues are fixed
- travis is now configured to run pylint on the `piqueserver` and `pyspades` directories (I'm not sure pylinting pyspades is a good idea due to the fact that it's cython?)

**Comment by noway** [comment]
if someone can remind me why i was arguing for `feature_server` that would be nice thanks

**Comment by swalladge** [comment]
Thats now piqueserver code done. (When I say done, I mean I've fixed as much as possible without making potentially breaking changes, suppressed other warnings, and commented/noted in the code where issues to be fixed are.)

**Comment by swalladge** [comment]
@feikname the linter is still being run on the pyspades directory (which i haven't worked on yet).

**Comment by swalladge** [comment]
By the way I'd now consider this properly ready for review. I'm not planning on making any more changes apart from issues raised during reviewing.

Also note that I have discovered some issues or bugs during coding this that were previously in the code, and thus I'm not planning on fixing those here - we can focus on the refactoring first, then once that's merged to master we can go bug hunting. :)

**Comment by noway** [comment]
:+1:

**Comment by noway** [comment]
Also I finally know why we kept feature_server. Because we haven't decided on the name yet at one point, but surely now it is save to change!

**Pull request merged**
