### PR TITLE
[WIP] pip fixes

### PR DESCRIPTION
**Pull request by noway421**
The main issue is that cython is being installed, but not being picked up by setup.py because the setup.py script is still running... would be nice if setup.py would just restart after `egg_info` command.

Tried to defer the import of cython, but then can't find a way to make cythonize work

### CODE REVIEW

**Comment by noway421** [comment]
this:https://github.com/h5py/h5py/blob/master/setup_build.py#L195

**Comment by noway421** [comment]
fixed cython, but now enet.so is not getting copied over

**Comment by swalladge** [comment]
I believe commit https://github.com/piqueserver/piqueserver/pull/38/commits/b17eb5e63fa2b4e8a4484fbc265b8b31ff9c9200 has fixed enet.so not being copied. The package_data entry didn't seem to do anything, so removed that for now. Now to work out if any other files in the `pyspades/enet/` directory needs to be ignored.

**Comment by noway421** [comment]
Do you need some more time or are we on the straight road to PyPi?

**Pull request merged**
