### PR TITLE
More refactoring

### PR DESCRIPTION
**Pull request by feikname**
The intention of this pull request is to make piqueserver code PEP8 compliant as much as possible.

### CODE REVIEW

**Comment by feikname** [comment]
I also changed the `feature_server` headers because I think they are more informative this way, but I can revert them if anyone wishes to.

**Comment by NotAFile** [comment]
I can't possibly look at all of this stuff but it seems to be good. This will create a ton of merge errors everywhere, but it needs to be done at some point.

**Comment by noway421** [comment]
👍

**Comment by noway421** [comment]
Too soon. Have to revert it. We will get it back.

**Pull request merged**
