### PR TITLE
add some player methods to irc

### LINKED ISSUE #510: Some commands crash when called through irc
**Describe the bug**

Some commands use methods of the game/server connection that aren't implemented for the irc connection, such as `send_lines`. This causes the command to crash, a traceback in the logs, and no feedback to the irc user.

**To Reproduce**

1. get a server running with irc enabled
2. call `!help` (reproducible with other commands too) from the irc channel
3. view logs

**Expected behavior**

for commands that should be available through irc: no crash

for commands that require to be called in-game: be not allowed to call it, with a feedback message.

### PR DESCRIPTION
**Pull request by NotAFile**
dcc6af4706 fixed these errors for ConsoleInput, but not IRC

closes #510

### CODE REVIEW

**Comment by NotAFile** [comment]
Note this is untested, I just did this based on swalladges's comments

**Comment by swalladge** [comment]
Ultimately it would be nice to have a neater consistent api for commands to use. This passing of the connection/irc/console object to the function feels fragile.

**Comment by NotAFile** [comment]
Indeed... but I'm not quite sure how else you'd do it? Perhaps some kind of `CommandCaller` wrapper object that you'd have to call `get_connection()` on to get a player reference? That would then err out and say "This command must be called from a player" or something?

I'm also not sure how you could change this in a backward-compatible manner.

**Comment by NotAFile** [comment]
Actually, scratch that... I wanted to make a new command API anyway! Wanted to get rid of global command registration in favor of multiple `CommandRegistry` objects. This would allow you to group commands for better documentation and rights management, as well as bringing us closer to being able to load and unload scripts at runtime.

**Pull request merged**
