### PR TITLE
Add chat links

### PR DESCRIPTION
**Pull request by NotAFile**
Not quite sure about the location or formatting yet, perhaps we can do some bikeshedding.

### CODE REVIEW

**Comment by feikname** [comment]
Yeah, the formatting looks weird to me.

How about including this info in one of the existing sections? (either FAQ, Contribute, or Development)

Also, the "Brought to you with ❤️ by the piqueserver team" at the foother looks broken to me on Chrome on WIndows 10, does it also affect anyone else?

**Screenshot:**
image

**Comment by NotAFile** [comment]
looks fine to me

**Comment by NotAFile** [comment]
Note: we have #piqueserver on freenode now too. If somebody could merge this that would be great.

**Comment by feikname** [comment]
I had totally forgotten about this PR, oops.

**Pull request merged**
