### PR TITLE
Pyenet update

### PR DESCRIPTION
**Pull request by noway421**
Updated to latest pyenet `master`. Tested with gamedig, `query.py` is working.

### CODE REVIEW

**Comment by NotAFile** [comment]
I'm not sure how useful it is to set this up considering our goal is to get pyenet onto pypi asap, but this kind of stuff is what git submodules were made for. Doing it this way lgtm for now though.

**Comment by noway421** [comment]
I agree with you completely re: both points. Git submodules are a good fit here, yes, but I personally find them very brittle and not easy to use (eg need more than simple clone to fetch the whole repo, problems with versioning). 

The goal is to get pyenet in pypi, yes, and I view this PR as a way to track that progress. It is an iterative step. We need the .patch file to track what changes are left to be merged, so might as well commit that to our `master`.

**Comment by swalladge** [comment]
I don't know how cython works so maybe I'm not the best reviewer here. :P Either way, it looks great and is a step closer to being able to use it directly from upstream, so nice work! :)

**Comment by feikname** [comment]
@noway421 is this ready to merge?

**Comment by noway421** [comment]
👍

**Pull request merged**
