### PR TITLE
Add unstable feature-exchange packet

### PR DESCRIPTION
**Pull request by NotAFile**
This would allow the client/server to check and send attributes to each other
in a standardized manner

### CODE REVIEW

**Comment by NotAFile** [comment]
cc @xtreme8000 @yvt for comment

**Comment by xtreme8000** [comment]
What would the additional data be used for? This is just to exchange feature availability, not to exchange data using an universal packet, right? I think a feature version number would suffice

**Comment by NotAFile** [comment]
this is now obsolete as we have designed a new extension system.

**Comment by NotAFile** [comment]
reopening so I don't forget to cherry pick the commits that accidentally landed on this branch

**Pull request closed without merging**
