### PR TITLE
Update airstrike2.py

### PR DESCRIPTION
**Pull request by Eneroh**
/a will now work when inputting command into chat

### CODE REVIEW

**Comment by NotAFile** [comment]
The problem here was that it would not show the message if an airstrike was available, right?

**Comment by NotAFile** [comment]
Actually, I don't see the problem here. What does this fix?

**Comment by Eneroh** [comment]
When you type /a it didn't count how many kills until you get until an airstrike. Minor fix. I tested the script with my server and it works so eh.

**Comment by NotAFile** [comment]
Oh, I see. That makes sense.

**Pull request merged**
